# configs/dataset.yaml
# ──────────────────────────────────────────────────────────────
# Stand-alone config used by generate.py
# All keys referenced in dataset_generator.py are declared here
# ──────────────────────────────────────────────────────────────
# ------------ dataset ------------

dataset:
  # generation parameters
  model_name: null # placeholder
  toxic_model_name: null # placeholder
  num_samples: null

  seed: 42
  train_samples: 3100  # Number of samples for training datasets
  test_samples: 600    # Number of samples for testing datasets

  max_new_tokens: 30
  batch_size: 256
  temperature: 1.0
  top_p: 1.0
  
  prompt_dataset: allenai/real-toxicity-prompts
  toxicity_metric: "profanity"  # options: toxicity, profanity, sexually_explicit, flirtation, identity_attack, threat, insult, severe_toxicity
  toxicity_threshold: 0.9         # threshold for filtering PROMPTS for TOXIC SPLIT
  non_toxic_threshold: 0.9        # used for NON-TOXIC splits

  
  # Prompt subset selection (for train/test splits)
  prompt_offset: null  # Start from this index in the filtered prompts
  same_test_prompt: true  # Use same prompts for toxic and non-toxic test datasets

  # Optional: sort dataset into toxic/non-toxic groups using a classifier
  sort_out_toxic_nontoxic: true
  sort_classifier: s-nlp/roberta_toxicity_classifier #facebook/roberta-hate-speech-dynabench-r4-target
  # threshold above which a sample is considered toxic
  sort_threshold: 0.7 # threshold for sorting toxic/non-toxic outputs

  #  IO / caching
  cache_dir: ${hydra:runtime.cwd}/datasets
  use_cached: false
  use_half_precision: null

# ------------ logging ------------
logging:
  use_wandb: false
  project_name: irl_dataset_gen
  wandb_mode: disabled
